### ISSUE TITLE
PROPOSAL

### ISSUE THREAD

**Issue by xcarpentier** [nandorojo/expo-firestore-offline-persistence#4]
Hi @nandorojo !

Thanks for this first draft package.

Would it be possible to work together to provide a solution that store files into [expo-filesystem](https://docs.expo.io/versions/latest/sdk/filesystem/) instead of `AsyncStorage` (ie. seems too slow) or `sqlite` (ie. seems not really adapted to this kind of storing thing)?

Also, do you think this is extendable to old fashion firebase or not at all?

**Comment by nandorojo** [comment]
Hey! Thanks for the issue.

1. This solution does use SQLite instead of AsyncStorage. As I mentioned in your other issue, the file using AsyncStorage is deprecated and not going to be used. It all comes down to the `polyfill` file, which uses expo-sqlite (see the last line). The in-memory localStorage is only meant to trick firestore into thinking we’re using it; it isn’t actually required for persisting the data. Expo SQLite does that for us :)

2. As for Firebase DB, possibly, although I’ve never used it before. Do you know how their persistence works? I’m biased since I think Firestore is much better 😇 If Firebase DB persistence relies on SQLite/indexeddb, then this package might work...

**Comment by xcarpentier** [comment]
Thanks for your responses!

I hope I will have a chance someday to use it, maybe soon, it seems a good solution then!
👍

**Comment by nandorojo** [comment]
Sounds good, let me know if you get the chance to!

If you decide to use Firestore, you can also check out my querying library: https://github.com/nandorojo/swr-firestore
